### ISSUE TITLE
Integración de dataset latinoamérica

### ISSUE THREAD

**Issue by ZurMaD** [dfuribez/COVID-19-Colombia#1]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En tu caso Colombia.

El formato del csv se está manejando acorde al formato global https://github.com/CSSEGISandData/COVID-19 para luego poder juntar la data.
Esto comprende las siguientes columnas:
![image](https://user-images.githubusercontent.com/28235457/77203239-ee717e80-6abd-11ea-9194-72f33246e6db.png)

En el caso de Colombia sería agrupados de esta forma:

![image](https://user-images.githubusercontent.com/28235457/77203265-03e6a880-6abe-11ea-82f8-36a9779ebb4c.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_pe

**Comment by dfuribez** [comment]
Hola @ZurMaD, sí, me interesa. Por favor coméntame más sobre el formato, ¿la idea es generar uno por día como en https://github.com/CSSEGISandData/COVID-19 o ir actualizando uno global con las columnas que ya mensionaste?

**Comment by ZurMaD** [comment]
@dfuribez , Sí ya que no tienen la resolución adecuada (solo índica país y los #s) en su base de datos sobre latinoamérica (Hay estudios que estan a la espera de tener esta base de datos que se quiere generar). La idea es hacer el mismo formato internacional pero con mayor control, he visto que los creadores son de otro continente y es dificil tener contacto directo, entonces se planteó empezar uno a nivel latinoamérica. Como en este csv que ya tiene el formato pero no la data 
![image](https://user-images.githubusercontent.com/28235457/77209537-81191a00-6acc-11ea-9126-d835de7beebd.png) https://github.com/DataScienceResearchPeru/covid-19_pe/blob/master/dsrp_covid_19_data/dsrp_covid_19_daily_reports/03-19-2020.csv

**Comment by dfuribez** [comment]
Ok, apúntame entonces.
