### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by everettk** [dfuribez/COVID-19-Colombia#2]
Hello! I'm a researcher at Google working on COVID-19 models. We found your repo of data for Colombia and we'd like to use it in a project.

Could you possibly add a LICENSE file to your repo, which would allow us to use the data for research purposes? The easiest license for us is Apache 2.0. (But if you had an objection, you could also use MIT license or another license that allows a commercial entity to use for research purposes.)

You can also let us know how you'd like your work to be cited so we can provide appropriate credit if the project is published.

Thanks for your work in collecting this data!

**Comment by dfuribez** [comment]
Hi @everettk the [site](https://www.datos.gov.co/Salud-y-Protecci-n-Social/Casos-positivos-de-COVID-19-en-Colombia/gt2j-8ykr/data) from where I'm getting the data is under  CC BY-SA 4.0 so I'm adding that one.

So, you can either use the official site or my repo (that I hope to get it update for the end of the week).

**Comment by everettk** [comment]
Thank you @dfuribez! That would be great. I'll check back later this week after you've updated and added the license file.

**Comment by dfuribez** [comment]
@everettk now the repo is up to date and the license was added.

**Comment by everettk** [comment]
Thanks @dfuribez!
